#!/bin/sh
# fbsetbg -l # sets the last background set, very useful and recommended.

# In the below commands the ampersand symbol (&) is required on all applications that do not terminate immediately.
# Failure to provide them will cause Fluxbox not to start.

# Source Xresources
xrdb -merge ~/.Xresources

# Change displays to not mirrored
xrandr --output DP-6 --mode 1920x1200 --left-of DP-4

# Set a reasonable key delay and rate
xset r rate 170 55

# Run xscreensaver in the background
xscreensaver -no-splash &

# Wallpaper Setter
feh --bg-scale ~/.fluxbox/backgrounds/Manjaro_ST3_one.png
compton &

# Network Manager
#nm-applet &

# Yabar Status Bar
yabar -c ~/.config/yabar/yabar.conf &

# Pulse Audio
#pulseaudio &
#pa-applet &

# Keepassx
keepassx &

# Pidgin
pidgin &

# Battery Icon Applet
#cbatticon &

# or if you want to keep a log, uncomment the below command and comment out the above command:
#exec /usr/bin/fluxbox -log ~/.fluxbox/log
/usr/bin/fluxbox -log ~/.fluxbox/log &
fbpid=$!

sleep 1
{
  # Open two terminal windows
  urxvt -title 'Right' &
  urxvt -title 'Left' &
}
wait $fbpid
